<?php
/**
 * @link https://github.com/Izumi-kun/yii2-lti-tool-provider
 * @copyright Copyright (c) 2024 Viktor Khokhryakov
 * @license http://opensource.org/licenses/BSD-3-Clause
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this platform?' => 'Вы уверены, что хотите удалить эту платформу?',
    'Cancel' => 'Отмена',
    'Create' => 'Создать',
    'Create LTI Platform' => 'Создать LTI платформу',
    'Created:' => 'Создан:',
    'Delete' => 'Удалить',
    'Disabled' => 'Отключен',
    'Enabled' => 'Включен',
    'Generate new secret' => 'Сгенерировать новый секрет',
    'Key' => 'Ключ',
    'Key:' => 'Ключ:',
    'LTI Platforms' => 'LTI платформы',
    'Last access:' => 'Последний доступ:',
    'Launch URL:' => 'URL запуска:',
    'Name' => 'Имя',
    'Platform #{num}' => 'Платформа #{num}',
    'Secret' => 'Секрет',
    'Sorry, there was an error connecting you to the application.' => 'К сожалению, произошла ошибка подключения к приложению.',
    'Status:' => 'Статус:',
    'Update' => 'Обновить',
    'Updated:' => 'Обновлен:',
];
