<?php
/**
 * @link https://github.com/Izumi-kun/yii2-lti-tool-provider
 * @copyright Copyright (c) 2024 Viktor Khokhryakov
 * @license http://opensource.org/licenses/BSD-3-Clause
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token service URL' => 'URL сервиса токена доступа',
    'Are you sure you want to delete this platform?' => 'Вы уверены, что хотите удалить эту платформу?',
    'Authentication request URL' => 'URL запроса аутентификации',
    'Authorization server ID' => 'ID сервера авторизации',
    'Cancel' => 'Отмена',
    'Client ID' => 'ID клиента',
    'Consumer key' => 'Ключ потребителя',
    'Consumer key has already been taken.' => 'Ключ потребителя уже занят.',
    'Create' => 'Создать',
    'Created:' => 'Создан:',
    'Delete' => 'Удалить',
    'Deployment ID' => 'ID развертывания',
    'Disabled' => 'Отключен',
    'Enabled' => 'Включен',
    'Generate new shared secret' => 'Сгенерировать новый общий секрет',
    'Key:' => 'Ключ:',
    'LTI Platforms' => 'LTI платформы',
    'Last access:' => 'Последний доступ:',
    'Launch URL:' => 'URL запуска:',
    'Message type not supported: {messageType}' => 'Тип сообщения не поддерживается: {messageType}',
    'Name' => 'Имя',
    'New LTI Platform' => 'Новая LTI платформа',
    'Platform #{num}' => 'Платформа #{num}',
    'Platform/Issuer ID' => 'ID платформы/издателя',
    'Public key' => 'Открытый ключ',
    'Public key is not valid.' => 'Открытый ключ недействителен.',
    'Public key:' => 'Открытый ключ:',
    'Public keyset URL' => 'URL набора открытых ключей',
    'Public keyset URL:' => 'URL набора открытых ключей:',
    'Shared secret' => 'Общий секрет',
    'Sorry, there was an error connecting you to the application.' => 'К сожалению, произошла ошибка подключения к приложению.',
    'Status:' => 'Статус:',
    'The combination of platform, client and deployment IDs has already been taken.' => 'Комбинация идентификаторов платформы, клиента и развертывания уже занята.',
    'Tool Details' => 'Детали инструмента',
    'Update' => 'Обновить',
    'Updated:' => 'Обновлен:',
];
