name: lint

on: [push, pull_request]

jobs:
    phpcs:
      runs-on: ubuntu-latest
      name: PHP_CodeSniffer
      steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.3'
            tools: cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run phpcs
        run: vendor/bin/phpcs -q --report=checkstyle | cs2pr
